### PR TITLE
Center cross 'close window' button on title bar

### PR DESCRIPTION
**Pull request by NTpspE**
Hi there, 

I've made a change that centres the X button in the titlebar.

### CODE REVIEW

**Comment by idoco** [comment]
Hey Nathan, thanks for the contribution!

Interestingly this behaves differently on my machine -

before

after

Can you please share an example of the problem the way you see it?
It might be that the issue is more complicated than what I see

**Comment by NTpspE** [comment]
Hi Idoco,

Ah sorry about that, I've looked into this again and it turns out it's some of Bootstrap's default CSS interfering with it. 

Bootstrap has 
`* {
-webkit-box-sizing: border-box;
box-sizing:border-box;
}`

By default, and so this is being applied to everything including this.
I've attached screenshots showing 3 different examples with the css. 

screen shot 2018-06-06 at 05 57 08
screen shot 2018-06-06 at 05 56 58
screen shot 2018-06-06 at 05 56 45


Will see if I can restyle to make this work with both Bootstrap and non-bootstrap sites.

All the best, 
Nathan

**Comment by NTpspE** [comment]
Hi Idoco, 

I've added 'alignItems' as a property now, and tested both with and without Bootstrap and this looks to centre the cross regardless of whether box-sizing is set or not. 

Please can you check out? :)

**Comment by idoco** [comment]
Thanks Nathan.
At first glance, this still behaves a differently with `alignItems: 'center'`, but I'll try to take a longer look at it on the weekend.

Does this [jsfiddle](https://jsfiddle.net/sczdyLh6/) reproduces the same conditions that you experience with bootstrap?

**Comment by NTpspE** [comment]
Hi Idoco, 

It does yeah - the jsfiddle you sent over shows like this for me across Safari, Firefox and Chrome on Macos - and also displays like this on Chrome Android and Safari iOS.

screen shot 2018-06-07 at 10 43 39

If I negate the box-sizing property from Bootstrap then it displays correctly like this: 

screen shot 2018-06-07 at 10 46 47

Whereas when I tested with alignItems: 'center' display: 'flex' on the component, both with and without Bootstrap had the cross properly centred for me. 

On (our) site that I'm adding this to, I've used my updated widget.js code so you can see it in action on https://gingeronline.netlify.com and if you remove the main stylesheet you should see that the chat box still has the cross centred.

**Pull request closed without merging**
